api/routes.py
from flask import Blueprint, render_template

api = Blueprint("api", __name__)

@api.route("/")
def index():
    return render_template("index.html")

@api.route("/events")
def events():
    return render_template("events.html")

main.py
from flask import Flask
from api.routes import api

app = Flask(__name__, template_folder="templates", static_folder="static")

app.register_blueprint(api)

if __name__ == "__main__":
    app.run(port=8000, debug=True)

templates/events.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Time Management</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='index.css') }}"
    />
  </head>
  <body>
    <div class="sidebar">
      <a href="{{ url_for('api.index') }}">Home</a>
      <a href="#">Calender</a>
      <a href="#">Settings</a>
      <a href="#">Profile</a>
      <button id="collapse"><</button>
    </div>
    <div class="content">
      <h1>Events</h1>
      <hr />
      <button id="open">></button>
    </div>
    <script src="{{ url_for('static', filename='script.js') }}"></script>
  </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Time Management</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='index.css') }}"
    />
  </head>
  <body>
    <div class="sidebar">
      <a href="#">Events</a>
      <a href="#">Calender</a>
      <a href="#">Settings</a>
      <a href="#">Profile</a>
      <button id="collapse"><</button>
    </div>
    <div class="content">
      <h1>Manage Your Time Better!</h1>
      <hr />
      <button id="open">></button>
    </div>
    <script src="{{ url_for('static', filename='script.js') }}"></script>
  </body>
</html>